server:
  port: '9080'
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: ArticleInput
          group: ArticleGroup
          binder: local_rabbit
        output:
          destination: ArticleInput
          group: ArticleGroup
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /