server:
  port: '9082'
spring:
  cloud:
    stream:
      bindings:
        output-article:
          destination: ArticleInput
          group: ArticleGroup
          binder: local_rabbit    
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /